export const actionTypes = {
	USER_INIT: 'USER_INIT',
	USER_LOGIN: 'USER_LOGIN',

	POSTS_LOADING: 'POSTS_LOADING',
	POSTS_LOADED: 'POSTS_LOADED',
	POSTS_ERROR: 'POSTS_ERROR',
	POSTS_LIKED: 'POSTS_LIKED',
	POSTS_REPOSTED: 'POSTS_REPOSTED',
	POSTS_ADDED: 'POSTS_ADDED',
	POSTS_REMOVED: 'POSTS_REMOVED',
}